import { HomeContent } from '../../app/core/models/home-content';

export const homeContent: HomeContent = {
  generic: {
    fileExplorer: 'Eksplorator Plików',
    terminal: 'Terminal',
    aboutMe: 'O Mnie',
    settings: 'Ustawienia',
    browser: 'Przeglądarka Plików',
    months: {
      jan: "styczeń",
      feb: "luty",
      mar: "marzec",
      apr: "kwiecień",
      may: "maj",
      jun: "czerwiec",
      jul: "lipiec",
      aug: "sierpień",
      sep: "wrzesień",
      oct: "październik",
      nov: "listopad",
      dec: "grudzień",
    },
  },
  desktop: {
    projects: "Projekty",
    reboot: "Restart"
  },
  fileExplorer:{
    quickAccess: 'Szybki Dostęp',
    emptyFolderMsg: 'Ten folder jest pusty',
    name: 'Nazwa',
    created: 'Utworzony',
    modified: 'Zmodyfikowany',
    starred: 'Ulubione',
  },
  rebootDialog:{
    line0: 'Wymagany restart',
    line1: 'Na pewno chcesz zrestartować swój system?',
    line2: 'Wszystkie zmiany zostaną utracone',
    reload: 'Restart',
  },
  settings:{
    fullscreen: 'Pełny Ekran',
  },
  projects:{
    journeycraft:{
      introduction:{
        project: "projekt",
        desc: "opis",
        descValue: "Pierwszy serwer Minecraft z trybem Journey Mode",
        time: "czas",
        status: "status",
        statusValue: "zarchiwizowany",
        techStack: "technologie",
      },
      intro:{
        header: "Intro",
        inShort: "W skrócie",
        inShortVal: "JourneyCraft to cały ekosystem utworzony wokół Minecrafta. Własne pluginy, integracja z Discordem, strona internetowa - wszystko zbudowane samodzielnie i hostowane na własnej infrastrukturze.",
        inShortImg: "Miejsce spawnu graczy na serwerze JourneyCraft",
        bg: "Tło projektu",
        bgVal: "Wszystko zaczęło się w grudniu 2020 roku, kiedy w zaledwie kilka dni powstał plugin wprowadzający do Minecrafta nowy tryb gry - Journey Mode (JM), inspirowany tym, wprowadzonym w maju tego samego roku do gry Terraria. Początkowo był to tylko mały serwer dla znajomych. Jeden z nich - Dominik - zainteresował się projektem i zaproponował współpracę przy większym, publicznym serwerze opartym o mój plugin. Nie byłbym sobą, gdybym się nie zgodził.",
        timeline: {
          header: "timeline",
          item1: "pierwsza grywalna wersja Journey Mode",
          item2: "rozpoczęcie pracy nad projektemn JourneyCraft",
          item3: "publiczne otwarcie serwera",
          item4: "zakończenie działalności serwera",
        },
      },
      details:{
        header: "Szczegóły projektu",
        aboutJM: "Jak działa Journey Mode?",
        aboutJMval1: "Journey Mode łączy w sobie cechy trybu kreatywnego i przetrwania. Gracz zbiera materiały podobnie jak na survivalu, ale po zebraniu jego określonej ilości może go odblokować - wtedy zyskuje nieograniczony dostęp do tego surowca. Mechanika odblokowywania przedmiotów wprowadza do gry zupełnie nowe wyzwanie - odblokowanie możliwie jak najwięcej.",
        aboutJMval2: "Cała mechanika była obsługiwana za pomocą trzech podstawowych komend. Gracz za pomocą",
        aboutJMval3: "może wyświetlić interfejs graficzny zawierający informację, jakie przedmioty dostępne są do odblokowania i ile trzeba ich zebrać. Dzięki",
        aboutJMval4: "możliwe jest odblokowanie przedmiotów. Po użyciu tej komendy plugin sprawdza, czy w ekwipunku gracza są zablokowane przedmioty w ilości wymaganej do ich odblokowania - jeżeli tak, zapisuje w bazie danych stosowną informację, a gracz może do woli korzystać z nowych zasobów. Odblokowanie przedmiotu nie dodawało go bezpośrednio do ekwipunku - gracz zyskiwał możliwość pobierania go bez ograniczeń za pomocą",
        aboutJMval5: "Komenda działa w dwóch trybach - tekstowym (np.",
        aboutJMval6: "- daje graczowi stack kamienia) lub graficznym (",
        aboutJMval7: "- otwiera interfejs, podobny do tego z trybu kreatywnego).",
        aboutJMimg: "Journey inventory, uruchomione komendą /j give",
        discordIntegration: "Integracja z Discordem",
        discordIntegrationVal1: "Jedną z wyróżniajacych funkcji serwera była integracja z Discordem. Ja stworzyłem dedykowanego discordowego bota, a Dominik napisał plugin do Minecrafta - dzięki wzajemnej komunikacji obu programów możliwa była synchronizacja danych gracza (nick, status, ranga, statystyki), a także informacji o samym serwerze gry (status, liczba graczy). Zarówno bot jak i plugin miały swoje HTTP API, za pomocą których odbywała się wzajemna komunikacja. Stworzenie takiego systemu było wymagającym, ale bardzo ciekawym wyzwaniem - wymagało od nas ścisłej współpracy.",
        discordIntegrationImg: "Statystyki gracza przesłane przez JourneyBota",
        discordIntegrationVal2: "Proces powiązania konta gracza z kontem Discord zaczynał się na serwerze Minecraft. Gracz wpisywał komendę",
        discordIntegrationVal3: "następnie plugin Dominika wysyłał zapytanie do bota. Ten sprawdzał, czy taki gracz jest u nas na serwerze - jeżeli tak, to wysyłał na Discordzie wiadomość do tego użytkownika. Ten miał kilkadziesiąt sekund na dodanie reakcji pod wiadomością bota. Po upływie tego czasu lub w momencie zostawienia reakcji bot odsyłał do API pluginu informację o tym, czy weryfikacja się powiodła. Gracz otrzymywał stosowny komunikat, a w przypadku pomyślnej werfyfikacji - dane były zapisywane w bazie. Od tego momentu aktywność gracza na serwerze gry była przesyłana do API bota, a ten modyfikował dane użytkownika na naszym serwerze Discord.",
        website: "Strona internetowa JC",
        websiteVal1: "Projekt nie byłby kompletny bez własnej witryny internetowej. Wprowadzał do gry zupełnie nowy tryb oraz wyjątkowe funkcjonalności, z ktorymi gracze Minecrafta mogli nie mieć wcześniej styczności. Dlatego tak ważne było przygotowanie strony, ze szczególnie dopracowaną sekcją Wiki. Gracze mogli przeczytać tam jak dokładnie działa JM oraz zapoznać się z innymi mechanikami, unikalnymi dla naszego serwera. Dodatkowo strona prezentowała statystki graczy. Wizualnie witryna była silnie inspirowana grą. Strona dostępna była pod adresem journeycraft.pl, aktualnie jej archiwalna wersja dostępna jest",
        websiteVal2: "tutaj",
        websiteVal3: ". Witryna w całości była zaprojektowana i wykonana przeze mnie.",
        websiteImg: "Strona Wiki",
        infrastructure: "Infrastruktura",
        infrastructureVal: "Pierwszy serwer z Journey Mode był hostowany na komputerze z odzysku pod kontrolą Ubuntu Server. Nie był to demon szybkości, ale umożliwiał płynną rozgrywkę mi i grupce znajomych. Pozwolił mi przećwiczyć w praktyce mechanizmy działania Linuxa oraz sieci komputerowych, które dotychczas znałem tylko w teorii. Z czasem jak projekt się rozrósł, serwer Minecraft i baza danych zostały przeniesione na mocniejszą maszynę Dominika, a bot oraz strona internetowa dostępne były na moim sprzęcie.",
        infrastructureImg: "Moje pierwsze podejście do hostingu Minecrafta - laptop w roli serwera",
      },
      summary:{
        header: "Podsumowanie",
        jcNow: "JourneyCraft z perspektywy czasu",
        jcNowVal: "Wspaniale było cofnąć się nieco w czasie i powspominać pracę nad JC. Ten projekt to były moje pierwsze kroki w bardzo wielu dziedzinach. Po raz pierwszy musiałem sprawić, żeby kilka niezależnych systemów współpracowało ze sobą i pierwszy raz projektowałem API. Dziś wiele rzeczy zrobiłbym inaczej - na pewno chętniej korzystał z Git-a, czy zupełnie inaczej stworzyłbym strukturę kodu. Mimo tego, uważam projekt za bardzo udany.",
      },
    },
  },
};