import { HomeContent } from '../../app/core/models/home-content';

export const homeContent: HomeContent = {
  generic: {
    fileExplorer: 'File Explorer',
    terminal: 'Terminal',
    aboutMe: 'About Me',
    settings: 'Settings',
    browser: 'File Browser',
    months: {
      jan: "January",
      feb: "February",
      mar: "March",
      apr: "April",
      may: "May",
      jun: "June",
      jul: "July",
      aug: "August",
      sep: "September",
      oct: "October",
      nov: "November",
      dec: "December",
    },
  },
  desktop: {
    projects: "Projects",
    reboot: "Reboot",
    hashi: "hashi.exe",
  },
  fileExplorer: {
    quickAccess: 'Quick Access',
    emptyFolderMsg: 'This folder is empty',
    name: 'Name',
    created: 'Created',
    modified: 'Modified',
    starred: 'Starred',
  },
  rebootDialog: {
    line0: 'System restart required',
    line1: 'Are you sure you want to reload your system?',
    line2: 'All changes will be lost',
    reload: 'Reload',
  },
  settings: {
    fullscreen: 'Fullscreen',
  },
  projects: {
    journeycraft: {
      introduction: {
        project: "project",
        desc: "description",
        descValue: "The first Minecraft server featuring Journey Mode",
        time: "time",
        status: "status",
        statusValue: "archived",
        techStack: "tech stack",
      },
      intro: {
        header: "Intro",
        inShort: "In short",
        inShortVal: "JourneyCraft is an entire ecosystem built around Minecraft. Custom plugins, Discord integration, a website - everything built from scratch and hosted on our own infrastructure.",
        inShortImg: "JourneyCraft players' spawn area",
        bg: "Project background",
        bgVal: "Everything started in December 2020, when, in just a few days, I created a plugin that introduced a new game mode to Minecraft - Journey Mode (JM), inspired by the one introduced to Terraria in May of the same year. Initially, it was just a small server for friends. One of them - Dominik - became interested in the project and suggested working together on a larger, public server built around my plugin. I wouldn’t be myself if I had said no.",
        timeline: {
          header: "timeline",
          item1: "first playable version of Journey Mode",
          item2: "work on the JourneyCraft project begins",
          item3: "server opens to the public",
          item4: "server shuts down",
        },
      },
      details: {
        header: "Project Details",
        aboutJM: "How does Journey Mode work?",
        aboutJMval1: "Journey Mode combines elements of Creative and Survival modes. Players collect materials just like in Survival, but after collecting a certain amount, they can unlock them, gaining unlimited access to that resource. The item unlocking mechanic introduces a completely new challenge to the game - unlocking as many items as possible.",
        aboutJMval2: "The entire mechanic was handled using three basic commands. Players could use",
        aboutJMval3: "to open a graphical interface showing which items were available to unlock and how many of each had to be collected. With",
        aboutJMval4: "players could unlock items. After using this command, the plugin checked whether the player's inventory contained the required number of the corresponding locked item. If so, it saved the appropriate information to the database, allowing the player to use the newly unlocked resource freely. Unlocking an item did not add it directly to the inventory - instead, it gave the player the ability to obtain unlimited amounts of it using",
        aboutJMval5: "The command worked in two modes - text-based (e.g.",
        aboutJMval6: "- gives the player a stack of stone) or graphical (",
        aboutJMval7: "- opens an interface similar to the one found in Creative mode).",
        aboutJMimg: "Journey inventory, opened with the /j give command",
        discordIntegration: "Discord Integration",
        discordIntegrationVal1: "One of the server's standout features was its Discord integration. I created a dedicated Discord bot, while Dominik developed a Minecraft plugin. Communication between the two programs made it possible to synchronize player data (username, status, rank, statistics), as well as information about the game server itself (status, player count). Both the bot and the plugin had their own HTTP APIs, which they used to communicate with each other. Creating such a system was a challenging but very interesting experience - it required close collaboration between us.",
        discordIntegrationImg: "Player statistics sent by JourneyBot",
        discordIntegrationVal2: "The process of linking a player's Minecraft account with their Discord account started on the Minecraft server. The player entered the command",
        discordIntegrationVal3: "Then, Dominik's plugin sent a request to the bot. The bot checked whether the player was on our server and, if so, sent a message to that user on Discord. The user then had several dozen seconds to react to the bot's message. Once that time had elapsed, or as soon as the user reacted, the bot sent the plugin's API information about whether the verification was successful. The player received an appropriate message and, if the verification was successful, the account link was saved to the database. From that moment on, the player's activity on the game server was sent to the bot's API, which used it to update the user's information on our Discord server.",
        website: "JC Website",
        websiteVal1: "The project would not have been complete without its own website. The plugin introduced a completely new game mode and unique features that Minecraft players might not have encountered before. That made it especially important to create a website with a particularly well-developed Wiki section. Players could read about exactly how JM worked and learn about other mechanics unique to our server. The website also displayed player statistics. Visually, the site was heavily inspired by the game itself. The website was available at journeycraft.pl; an archived version is currently available",
        websiteVal2: "here",
        websiteVal3: ". I designed and built the entire website myself.",
        websiteImg: "The Wiki page",
        infrastructure: "Infrastructure",
        infrastructureVal: "The first Journey Mode server was hosted on an old computer running Ubuntu Server. It was no speed demon, but it provided a smooth experience for me and a small group of friends. It also gave me an opportunity to gain hands-on experience with Linux and computer networking, which until then I had only known in theory. As the project grew, the Minecraft server and database were moved to a more powerful machine owned by Dominik, while the bot and website were hosted on my own hardware.",
        infrastructureImg: "My first attempt at hosting a Minecraft server - a laptop serving as the game server",
      },
      summary: {
        header: "Summary",
        jcNow: "JourneyCraft in Retrospect",
        jcNowVal: "It was great to take a step back in time and reminisce about working on JC. This project was my first experience in many different areas. For the first time, I had to make several independent systems work together, and I designed an API for the first time. Looking back, there are many things I would do differently today - I would certainly make more use of Git, for example, and I would structure the code completely differently. Despite that, I consider the project a great success.",
      },
    },
    fdd: {
      stack:{
        electronics: "circuit design",
        soldering: "soldering",
      },
      introduction: {
        project: "project",
        desc: "description",
        descValue: "Floppy disk drives as a musical instrument",
        time: "time",
        status: "status",
        statusValue: "completed",
        techStack: "technologies",
      },
      intro: {
        header: "Intro",
        inShort: "In short",
        inShortVal: "This project is an attempt to turn an simple toy into an unusual musical instrument. It combines electronics, programming, and a slightly unconventional approach to making music.",
        video1Caption: 'A theme from "Blinding Lights" - The Weeknd',
        bg: "Project background",
        bgVal: "Inspired by videos I had seen online, I decided to build my own setup for making floppy disk drives play music. Initially, it was simply a way to start learning Arduino programming - a fun project I could also show off at school. The original controller simply had a melody programmed into it, which it played through the FDD. A few years later, however, I returned to the project with new skills and a new idea - this time, I wanted to turn the floppy disk drives into a fully-fledged, interactive instrument that could actually be played.",
        video2Caption: '"Barka" played on one of the first versions of the project from 2020',
        finalVersionImg: "Final version of the project - interactive instrument",
        timeline: {
          header: "timeline",
          item1: "Creating the first version of an Arduino library for playing music using an FDD",
          item2: 'Returning to the project to record "Habits" for a school project',
          item3: "Returning to the project after several years and starting work on modifying the keyboard",
          item4: "Completing the instrument and finishing the project",
        },
      },
      firstVersion: {
        header: "First version of the project",
        howItWorks: "How does a floppy disk drive become an instrument?",
        howItWorksVal1: "Floppy disk drives are equipped with stepper motors that control the movement of the read/write head. When the motor takes steps at a specific frequency, it produces a sound at the corresponding pitch. By controlling the motor's speed, we can control the pitch of the sound.",
        howItWorksVal2: "Floppy disk drives have a 34-pin connector, four of which are particularly important when it comes to playing music:",
        howItWorksList1: "enables the FDD if pulled down",
        howItWorksList2: "direction of head movement",
        howItWorksList3: "one motor step",
        howItWorksList4: "track zero detection",
        biggestChallenge: "The biggest challenge - one core, two drives",
        biggestChallengeVal1: "I wanted two floppy disk drives to be able to play independently, controlled by a single-core Atmega. With one drive, everything was simple - all I had to do was use the",
        biggestChallengeVal2: " function, since blocking the main thread wasn't an issue. Things became a little more complicated when adding a second drive. In addition to playing a sound at a specific frequency, I also had to control the position of both heads.",
        biggestChallengeVal3: "The solution was a single loop for the main thread, running at the processor's clock speed with no delays. The main loop repeatedly checked whether it was time to generate the next step for either of the drives. The same loop also controlled the position of the head (the state of the",
        biggestChallengeVal4: " pin) and changed the state of the",
        biggestChallengeVal5: " pin when necessary. This made it possible to handle additional drives without having to create a separate thread for each one.",
        videoCaption: 'Tove Lo "Habits" - Hippie Sabotage Remix',
      },
      keyboard: {
        header: "Keyboard",
        keyHandling: "Key handling",
        keyHandlingVal: "The keyboard of my instrument works similarly to a typical computer membrane keyboard. Each key had a membrane underneath it that connected two traces - a column and a row. To determine which keys are pressed, the controller applies a high signal to each row in sequence and checks which column returns a logical 1. The remaining row pins must be left in a high-impedance state, while the columns are configured as inputs with pull-up resistors. I used both cores of the microcontroller - one generated signals for the FDDs, while the other handled the keyboard.",
        prototypeImg: "Prototype on a breadboard",
        electronics: "Electronics",
        electronicsVal: "The mainboard for this project was relatively simple - but at the same time, it was one of the first boards I had designed and built. It contains a microcontroller - a Raspberry Pi Pico with an RP2040 chip, a logic level converter (floppy disk drives operate at 5V, while the RPi uses 3.3V), a UCY7402 chip (NOR gates connected in a way that makes them function as NOT gates), as well as a capacitor and connectors for the power supply (from an ATX computer power supply), keyboard, and FDDs. I made the traces by soldering them directly onto a prototyping board.",
        motherboardFrontImg: "Mainboard - top",
        motherboardBackImg: "Mainboard - bottom",
        improvements: "Improvements over the previous version",
        improvementsVal: "The first version of the project had two main drawbacks: I had to keep track of the direction of the head, and the drive produced a \"clicking\" sound whenever the direction changed. I solved both problems with a single modification - shorting the",
        improvementsVal2: " and",
        improvementsVal3: " pins. Thanks to this modification, when the head was on track 0, the",
        improvementsVal4: " pin pulled the",
        improvementsVal5: " pin low, causing the head to move away from the motor. A single step was enough for the",
        improvementsVal6: " pin to return to a logical 1 - at that point, the head reversed direction towards the motor, moving back onto track zero. As a result, the controller no longer had to keep track of the head's position at all - this simplified both the code and the mainboard, and the controller only needed a single wire to control the floppy disk drive.",
        connectorImg: "Clever short between the Direction and Track 0 pins",
        insideImg: "Inside the modified keyboard",
        finalVideoCaption: 'A theme from "Shelter" by Porter Robinson & Madeon',
      },
      summary: {
        header: "Summary",
        lesson: "A lesson beyond music",
        lessonVal1: "Working on this project was both enjoyable and educational. I had to do some research online to figure out the pinout of floppy disk drives, and I also had to think carefully about the algorithms used to play the melodies. The controller board was one of the first boards I had ever built, giving me practical skills that later proved useful when building more complex circuits.",
        lessonVal2: "Perhaps unsurprisingly, there are some things I would do differently today. Above all, I would improve the aesthetics of the instrument. Today, I have access to 3D printing, which offers almost unlimited possibilities for creating enclosures, mounts, and covers.",
        finalVideoCaption: 'A theme from "Faded" by Alan Walker',
      },
    },
  },
};