import { HomeContent } from '../../app/core/models/home-content';

export const homeContent: HomeContent = {
  generic: {
    fileExplorer: 'File Explorer',
    terminal: 'Terminal',
    aboutMe: 'About Me',
    settings: 'Settings',
    browser: 'File Browser',
    months: {
      jan: "January",
      feb: "February",
      mar: "March",
      apr: "April",
      may: "May",
      jun: "June",
      jul: "July",
      aug: "August",
      sep: "September",
      oct: "October",
      nov: "November",
      dec: "December",
    },
  },
  desktop: {
    projects: "Projects",
    reboot: "Reboot"
  },
  fileExplorer:{
    quickAccess: 'Quick Access',
    emptyFolderMsg: 'This folder is empty',
    name: 'Name',
    created: 'Created',
    modified: 'Modified',
    starred: 'Starred',
  },
  rebootDialog:{
    line0: 'System restart required',
    line1: 'Are you sure you want to reload your system?',
    line2: 'All changes will be lost',
    reload: 'Reload',
  },
  settings:{
    fullscreen: 'Fullscreen',
  },
  projects:{
    journeycraft:{
      introduction:{
        project: "project",
        desc: "description",
        descValue: "The first Minecraft server featuring Journey Mode",
        time: "time",
        status: "status",
        statusValue: "archived",
        techStack: "tech stack",
      },
      intro:{
        header: "Intro",
        inShort: "In short",
        inShortVal: "JourneyCraft is an entire ecosystem built around Minecraft. Custom plugins, Discord integration, a website - everything built from scratch and hosted on our own infrastructure.",
        inShortImg: "JourneyCraft players' spawn area",
        bg: "Project background",
        bgVal: "Everything started in December 2020, when, in just a few days, I created a plugin that introduced a new game mode to Minecraft - Journey Mode (JM), inspired by the one introduced to Terraria in May of the same year. Initially, it was just a small server for friends. One of them - Dominik - became interested in the project and suggested working together on a larger, public server built around my plugin. I wouldn’t be myself if I had said no.",
        timeline: {
          header: "timeline",
          item1: "first playable version of Journey Mode",
          item2: "work on the JourneyCraft project begins",
          item3: "server opens to the public",
          item4: "server shuts down",
        },
      },
      details:{
        header: "Project Details",
        aboutJM: "How does Journey Mode work?",
        aboutJMval1: "Journey Mode combines elements of Creative and Survival modes. Players collect materials just like in Survival, but after collecting a certain amount, they can unlock them, gaining unlimited access to that resource. The item unlocking mechanic introduces a completely new challenge to the game - unlocking as many items as possible.",
        aboutJMval2: "The entire mechanic was handled using three basic commands. Players could use",
        aboutJMval3: "to open a graphical interface showing which items were available to unlock and how many of each had to be collected. With",
        aboutJMval4: "players could unlock items. After using this command, the plugin checked whether the player's inventory contained the required number of the corresponding locked item. If so, it saved the appropriate information to the database, allowing the player to use the newly unlocked resource freely. Unlocking an item did not add it directly to the inventory - instead, it gave the player the ability to obtain unlimited amounts of it using",
        aboutJMval5: "The command worked in two modes - text-based (e.g.",
        aboutJMval6: "- gives the player a stack of stone) or graphical (",
        aboutJMval7: "- opens an interface similar to the one found in Creative mode).",
        aboutJMimg: "Journey inventory, opened with the /j give command",
        discordIntegration: "Discord Integration",
        discordIntegrationVal1: "One of the server's standout features was its Discord integration. I created a dedicated Discord bot, while Dominik developed a Minecraft plugin. Communication between the two programs made it possible to synchronize player data (username, status, rank, statistics), as well as information about the game server itself (status, player count). Both the bot and the plugin had their own HTTP APIs, which they used to communicate with each other. Creating such a system was a challenging but very interesting experience - it required close collaboration between us.",
        discordIntegrationImg: "Player statistics sent by JourneyBot",
        discordIntegrationVal2: "The process of linking a player's Minecraft account with their Discord account started on the Minecraft server. The player entered the command",
        discordIntegrationVal3: "Then, Dominik's plugin sent a request to the bot. The bot checked whether the player was on our server and, if so, sent a message to that user on Discord. The user then had several dozen seconds to react to the bot's message. Once that time had elapsed, or as soon as the user reacted, the bot sent the plugin's API information about whether the verification was successful. The player received an appropriate message and, if the verification was successful, the account link was saved to the database. From that moment on, the player's activity on the game server was sent to the bot's API, which used it to update the user's information on our Discord server.",
        website: "JC Website",
        websiteVal1: "The project would not have been complete without its own website. The plugin introduced a completely new game mode and unique features that Minecraft players might not have encountered before. That made it especially important to create a website with a particularly well-developed Wiki section. Players could read about exactly how JM worked and learn about other mechanics unique to our server. The website also displayed player statistics. Visually, the site was heavily inspired by the game itself. The website was available at journeycraft.pl; an archived version is currently available",
        websiteVal2: "here",
        websiteVal3: ". I designed and built the entire website myself.",
        websiteImg: "The Wiki page",
        infrastructure: "Infrastructure",
        infrastructureVal: "The first Journey Mode server was hosted on an old computer running Ubuntu Server. It was no speed demon, but it provided a smooth experience for me and a small group of friends. It also gave me an opportunity to gain hands-on experience with Linux and computer networking, which until then I had only known in theory. As the project grew, the Minecraft server and database were moved to a more powerful machine owned by Dominik, while the bot and website were hosted on my own hardware.",
        infrastructureImg: "My first attempt at hosting a Minecraft server - a laptop serving as the game server",
      },
      summary:{
        header: "Summary",
        jcNow: "JourneyCraft in Retrospect",
        jcNowVal: "It was great to take a step back in time and reminisce about working on JC. This project was my first experience in many different areas. For the first time, I had to make several independent systems work together, and I designed an API for the first time. Looking back, there are many things I would do differently today - I would certainly make more use of Git, for example, and I would structure the code completely differently. Despite that, I consider the project a great success.",
      },
    },
  },
};