import { HomeContent } from '../../app/core/models/home-content';

export const homeContent: HomeContent = {
  generic: {
    fileExplorer: 'File Explorer',
    terminal: 'Terminal',
    aboutMe: 'About Me',
    settings: 'Settings',
    browser: 'File Browser',
    months: {
      jan: "January",
      feb: "February",
      mar: "March",
      apr: "April",
      may: "May",
      jun: "June",
      jul: "July",
      aug: "August",
      sep: "September",
      oct: "October",
      nov: "November",
      dec: "December",
    },
  },
  desktop: {
    projects: "Projects",
    getInTouch: "Get in touch",
    reboot: "Reboot",
    hashi: "hashi.exe",
  },
  fileExplorer: {
    quickAccess: 'Quick Access',
    emptyFolderMsg: 'This folder is empty',
    name: 'Name',
    created: 'Created',
    modified: 'Modified',
    starred: 'Starred',
  },
  rebootDialog: {
    line0: 'System restart required',
    line1: 'Are you sure you want to reload your system?',
    line2: 'All changes will be lost',
    reload: 'Reload',
  },
  settings: {
    fullscreen: 'Fullscreen',
  },
  about: {
    header: "I'm a software developer, but I don't limit myself to just writing code.",
    p1: "I work on software development on a daily basis, and in my free time I enjoy experimenting with technology. I work on my own projects - designing electronic circuits, 3D-printing parts, and running a homelab. I'm also interested in astrophotography, which often becomes an excuse to build something of my own.",
    p2: "I enjoy projects that require stepping outside a single field - learning a new technology, designing a solution from scratch, or combining seemingly unrelated areas.",
    p3: "I'm a self-directed learner, and I learn by building - from an idea, through experiments and prototypes, to a working solution.",
  },
  projects: {
    journeycraft: {
      introduction: {
        project: "project",
        desc: "description",
        descValue: "The first Minecraft server featuring Journey Mode",
        time: "time",
        status: "status",
        statusValue: "archived",
        techStack: "tech stack",
      },
      intro: {
        header: "Intro",
        inShort: "In short",
        inShortVal: "JourneyCraft is an entire ecosystem built around Minecraft. Custom plugins, Discord integration, a website - everything built from scratch and hosted on our own infrastructure.",
        inShortImg: "JourneyCraft players' spawn area",
        bg: "Project background",
        bgVal: "Everything started in December 2020, when, in just a few days, I created a plugin that introduced a new game mode to Minecraft - Journey Mode (JM), inspired by the one introduced to Terraria in May of the same year. Initially, it was just a small server for friends. One of them - Dominik - became interested in the project and suggested working together on a larger, public server built around my plugin. I wouldn't be myself if I had said no.",
        timeline: {
          header: "timeline",
          item1: "first playable version of Journey Mode",
          item2: "work on the JourneyCraft project begins",
          item3: "server opens to the public",
          item4: "server shuts down",
        },
      },
      details: {
        header: "Project Details",
        aboutJM: "How does Journey Mode work?",
        aboutJMval1: "Journey Mode combines elements of Creative and Survival modes. Players collect materials just like in Survival, but after collecting a certain amount, they can unlock them, gaining unlimited access to that resource. The item unlocking mechanic introduces a completely new challenge to the game - unlocking as many items as possible.",
        aboutJMval2: "The entire mechanic was handled using three basic commands. Players could use",
        aboutJMval3: "to open a graphical interface showing which items were available to unlock and how many of each had to be collected. With",
        aboutJMval4: "players could unlock items. After using this command, the plugin checked whether the player's inventory contained the required number of the corresponding locked item. If so, it saved the appropriate information to the database, allowing the player to use the newly unlocked resource freely. Unlocking an item did not add it directly to the inventory - instead, it gave the player the ability to obtain unlimited amounts of it using",
        aboutJMval5: "The command worked in two modes - text-based (e.g.",
        aboutJMval6: "- gives the player a stack of stone) or graphical (",
        aboutJMval7: "- opens an interface similar to the one found in Creative mode).",
        aboutJMimg: "Journey inventory, opened with the /j give command",
        discordIntegration: "Discord Integration",
        discordIntegrationVal1: "One of the server's standout features was its Discord integration. I created a dedicated Discord bot, while Dominik developed a Minecraft plugin. Communication between the two programs made it possible to synchronize player data (username, status, rank, statistics), as well as information about the game server itself (status, player count). Both the bot and the plugin had their own HTTP APIs, which they used to communicate with each other. Creating such a system was a challenging but very interesting experience - it required close collaboration between us.",
        discordIntegrationImg: "Player statistics sent by JourneyBot",
        discordIntegrationVal2: "The process of linking a player's Minecraft account with their Discord account started on the Minecraft server. The player entered the command",
        discordIntegrationVal3: "Then, Dominik's plugin sent a request to the bot. The bot checked whether the player was on our server and, if so, sent a message to that user on Discord. The user then had several dozen seconds to react to the bot's message. Once that time had elapsed, or as soon as the user reacted, the bot sent the plugin's API information about whether the verification was successful. The player received an appropriate message and, if the verification was successful, the account link was saved to the database. From that moment on, the player's activity on the game server was sent to the bot's API, which used it to update the user's information on our Discord server.",
        website: "JC Website",
        websiteVal1: "The project would not have been complete without its own website. The plugin introduced a completely new game mode and unique features that Minecraft players might not have encountered before. That made it especially important to create a website with a particularly well-developed Wiki section. Players could read about exactly how JM worked and learn about other mechanics unique to our server. The website also displayed player statistics. Visually, the site was heavily inspired by the game itself. The website was available at journeycraft.pl; an archived version is currently available",
        websiteVal2: "here",
        websiteVal3: ". I designed and built the entire website myself.",
        websiteImg: "The Wiki page",
        infrastructure: "Infrastructure",
        infrastructureVal: "The first Journey Mode server was hosted on an old computer running Ubuntu Server. It was no speed demon, but it provided a smooth experience for me and a small group of friends. It also gave me an opportunity to gain hands-on experience with Linux and computer networking, which until then I had only known in theory. As the project grew, the Minecraft server and database were moved to a more powerful machine owned by Dominik, while the bot and website were hosted on my own hardware.",
        infrastructureImg: "My first attempt at hosting a Minecraft server - a laptop serving as the game server",
      },
      summary: {
        header: "Summary",
        jcNow: "JourneyCraft in Retrospect",
        jcNowVal: "It was great to take a step back in time and reminisce about working on JC. This project was my first experience in many different areas. For the first time, I had to make several independent systems work together, and I designed an API for the first time. Looking back, there are many things I would do differently today - I would certainly make more use of Git, for example, and I would structure the code completely differently. Despite that, I consider the project a great success.",
      },
    },
    fdd: {
      stack: {
        electronics: "circuit design",
        soldering: "soldering",
      },
      introduction: {
        project: "project",
        desc: "description",
        descValue: "Floppy disk drives as a musical instrument",
        time: "time",
        status: "status",
        statusValue: "completed",
        techStack: "tech stack",
      },
      intro: {
        header: "Intro",
        inShort: "In short",
        inShortVal: "This project is an attempt to turn an simple toy into an unusual musical instrument. It combines electronics, programming, and a slightly unconventional approach to making music.",
        video1Caption: 'A theme from "Blinding Lights" - The Weeknd',
        bg: "Project background",
        bgVal: "Inspired by videos I had seen online, I decided to build my own setup for making floppy disk drives play music. Initially, it was simply a way to start learning Arduino programming - a fun project I could also show off at school. The original controller simply had a melody programmed into it, which it played through the FDD. A few years later, however, I returned to the project with new skills and a new idea - this time, I wanted to turn the floppy disk drives into a fully-fledged, interactive instrument that could actually be played.",
        video2Caption: '"Barka" played on one of the first versions of the project from 2020',
        finalVersionImg: "Final version of the project - interactive instrument",
        timeline: {
          header: "timeline",
          item1: "Creating the first version of an Arduino library for playing music using an FDD",
          item2: 'Returning to the project to record "Habits" for a school project',
          item3: "Returning to the project after several years and starting work on modifying the keyboard",
          item4: "Completing the instrument and finishing the project",
        },
      },
      firstVersion: {
        header: "First version of the project",
        howItWorks: "How does a floppy disk drive become an instrument?",
        howItWorksVal1: "Floppy disk drives are equipped with stepper motors that control the movement of the read/write head. When the motor takes steps at a specific frequency, it produces a sound at the corresponding pitch. By controlling the motor's speed, we can control the pitch of the sound.",
        howItWorksVal2: "Floppy disk drives have a 34-pin connector, four of which are particularly important when it comes to playing music:",
        howItWorksList1: "enables the FDD if pulled down",
        howItWorksList2: "direction of head movement",
        howItWorksList3: "one motor step",
        howItWorksList4: "track zero detection",
        biggestChallenge: "The biggest challenge - one core, two drives",
        biggestChallengeVal1: "I wanted two floppy disk drives to be able to play independently, controlled by a single-core Atmega. With one drive, everything was simple - all I had to do was use the",
        biggestChallengeVal2: " function, since blocking the main thread wasn't an issue. Things became a little more complicated when adding a second drive. In addition to playing a sound at a specific frequency, I also had to control the position of both heads.",
        biggestChallengeVal3: "The solution was a single loop for the main thread, running at the processor's clock speed with no delays. The main loop repeatedly checked whether it was time to generate the next step for either of the drives. The same loop also controlled the position of the head (the state of the",
        biggestChallengeVal4: " pin) and changed the state of the",
        biggestChallengeVal5: " pin when necessary. This made it possible to handle additional drives without having to create a separate thread for each one.",
        videoCaption: 'Tove Lo "Habits" - Hippie Sabotage Remix',
      },
      keyboard: {
        header: "Keyboard",
        keyHandling: "Key handling",
        keyHandlingVal: "The keyboard of my instrument works similarly to a typical computer membrane keyboard. Each key had a membrane underneath it that connected two traces - a column and a row. To determine which keys are pressed, the controller applies a high signal to each row in sequence and checks which column returns a logical 1. The remaining row pins must be left in a high-impedance state, while the columns are configured as inputs with pull-up resistors. I used both cores of the microcontroller - one generated signals for the FDDs, while the other handled the keyboard.",
        prototypeImg: "Prototype on a breadboard",
        electronics: "Electronics",
        electronicsVal: "The mainboard for this project was relatively simple - but at the same time, it was one of the first boards I had designed and built. It contains a microcontroller - a Raspberry Pi Pico with an RP2040 chip, a logic level converter (floppy disk drives operate at 5V, while the RPi uses 3.3V), a UCY7402 chip (NOR gates connected in a way that makes them function as NOT gates), as well as a capacitor and connectors for the power supply (from an ATX computer power supply), keyboard, and FDDs. I made the traces by soldering them directly onto a breadboard.",
        motherboardFrontImg: "Mainboard - top",
        motherboardBackImg: "Mainboard - bottom",
        improvements: "Improvements over the previous version",
        improvementsVal: "The first version of the project had two main drawbacks: I had to keep track of the direction of the head, and the drive produced a \"clicking\" sound whenever the direction changed. I solved both problems with a single modification - shorting the",
        improvementsVal2: " and",
        improvementsVal3: " pins. Thanks to this modification, when the head was on track 0, the",
        improvementsVal4: " pin pulled the",
        improvementsVal5: " pin low, causing the head to move away from the motor. A single step was enough for the",
        improvementsVal6: " pin to return to a logical 1 - at that point, the head reversed direction towards the motor, moving back onto track zero. As a result, the controller no longer had to keep track of the head's position at all - this simplified both the code and the mainboard, and the controller only needed a single wire to control the floppy disk drive.",
        connectorImg: "Clever short between the Direction and Track 0 pins",
        insideImg: "Inside the modified keyboard",
        finalVideoCaption: 'A theme from "Shelter" by Porter Robinson & Madeon',
      },
      summary: {
        header: "Summary",
        lesson: "A lesson beyond music",
        lessonVal1: "Working on this project was both enjoyable and educational. I had to do some research online to figure out the pinout of floppy disk drives, and I also had to think carefully about the algorithms used to play the melodies. The controller board was one of the first boards I had ever built, giving me practical skills that later proved useful when building more complex circuits.",
        lessonVal2: "Perhaps unsurprisingly, there are some things I would do differently today. Above all, I would improve the aesthetics of the instrument. Today, I have access to 3D printing, which offers almost unlimited possibilities for creating enclosures, mounts, and covers.",
        finalVideoCaption: 'A theme from "Faded" by Alan Walker',
      },
    },
    bsodmaker: {
      introduction: {
        project: "project",
        desc: "description",
        descValue: "A Windows 10 experience in your browser",
        time: "time",
        status: "status",
        statusValue: "completed",
        techStack: "tech stack",
      },
      intro: {
        header: "Intro",
        inShort: "In short",
        inShortVal: "Bsodmaker is an unusual frontend experiment: a faithful, interactive recreation of the Windows 10 interface, paired with a fully editable Blue Screen of Death.",
        website: "https://bsodmaker.mchudzinski.dev/",
        bsodImg: "A BSoD generated with the tool",
        bsodImgCaption: "A BSoD generated with the tool",
        bg: "Project background",
        bgVal: "It all started with the idea of recreating a BSoD in the browser. As more ideas came along, the project grew beyond a single screen - a menu, interactive windows, and other elements inspired by Windows 10 were added along the way.",
        timeline: {
          header: "Timeline",
          item1: "Work on the project begins",
          item2: "bsodmaker.net domain registered",
          item3: "Working version of the website goes live",
          item4: "bsodmaker.net domain expires",
          item5: "Project migrated to its current address - bsodmaker.mchudzinski.dev",
        },
      },
      features: {
        header: "Features",
        bsodEditor: "BSoD editing",
        bsodEditorVal: "The main feature of the tool is its BSoD editor. Using",
        bsodEditorVal2: "users can easily enter their own data. The QR code contents are editable too.",
        windowsUI: "A UI inspired by Windows 10",
        windowsUIVal: "One of the biggest challenges was faithfully recreating how Windows windows behave in the browser, using only JS and jQuery. I ended up writing what was essentially a small library to handle every possible window interaction.",
        windowsUIImg: "Website interface inspired by the Windows 10 UI",
        prank: "One tool, two ways to prank",
        prankVal1: "The tool lets you download your edited BSoD in Full HD straight to your device. The image can be used as a wallpaper or a login screen background. The website uses the",
        prankVal2: "library to convert the rendered page into an image that can then be downloaded. Because screen resolutions vary between devices, a second, invisible BSoD with a fixed resolution sits underneath the editable one. When the library captures the page, it actually captures this hidden version, so the screenshot always has the same resolution regardless of the device.",
        prankVal3: "The download feature isn't the only way to pull off the prank - it can also be done directly in the browser. The tool can enter fullscreen mode and hide the cursor, making the BSoD look almost indistinguishable from the real system screen. The UI is still available, and you can press the",
        prankVal4: "key to navigate.",
        mobileLinux: "Mobile and Linux support",
        mobileLinuxVal1: "I did my best to make the editor just as comfortable on phones and tablets as on a desktop. The menu is slightly simplified, while the windows remain fully interactive.",
        mobileLinuxVal2: "Surprisingly, Linux turned out to be the trickier platform. The original bluescreen uses the",
        mobileLinuxVal3: "font, which comes built into Windows, but I couldn't just bundle its file with the project and ship it to users of other systems. The fix was to use",
        mobileLinuxVal4: "as a fallback. It looks similar, and its license doesn't restrict its use in my own projects.",
      },
      summary: {
        header: "Summary",
        statistics: "Statistics",
        statisticsVal1: "I've been collecting visitor statistics since the site first went online. As of writing (September 30, 2026), it has had over 390,000 visits, including roughly 260,000 unique visitors.",
        statisticsVal2: "In July 2024, I created a page for the project on",
        statisticsVal3: "I raised $15. It wasn't life-changing money, but it covered the domain for another year and, more importantly, it was a nice sign that someone found the project interesting enough to support it.",
        statisticsVal4: "An",
        statisticsVal5: "was also published about the tool. I'm very happy that bsodmaker was so warmly received.",
        buyMeACoffee: "Buy Me a Coffee",
        korbenArticle: "independent article on korben.info",
        domain: "What happened to the bsodmaker.net domain?",
        domainVal: "I owned the domain for two years. After that, I decided to move bsodmaker to another address I already maintain. The domain is now used by someone else, who runs a similar tool there.",
        retrospective: "Bsodmaker in retrospect",
        retrospectiveVal: "With the skills I have today, bsodmaker practically begs to be rebuilt in Angular. Back in 2024, I didn't even know that a solution existed that I'd now consider the obvious choice. The visual result would probably be very similar, but the code would certainly be cleaner and more readable.",
      },
    },
    tradingbot: {
      introduction: {
        project: "project",
        desc: "description",
        descValue: "Autonomous cryptocurrency trading bot",
        time: "time",
        status: "status",
        statusValue: "archived",
        techStack: "tech stack",
      },
      intro: {
        header: "Intro",
        inShort: "In short",
        inShortVal: "Who wouldn't want to have a lot of money? The trading bot was supposed to be one of the ways to grow my capital. It connected to an exchange, fetched data, placed an order and... lost money. Although it didn't make me a millionaire, it was an interesting programming challenge.",
        inShortImg: "A loss of around 20 USDT during one of the bot's first months of operation",
        bg: "Project background",
        bgVal: "The project was created with one goal - it was supposed to make money on its own. The plan was to build a bot that would autonomously trade crypto assets with minimal supervision. Reality put this idea to the test, and the project turned out to be much more complex, both in the code and, above all, in coming up with the right strategy",
        timeline: {
          header: "timeline",
          item1: "Started working on the project, first experiments with the Binance API",
          item2: "Launched the first manually controlled version of the bot on my own server",
          item3: "Created tools for simulating the bot's operation without using any capital",
          item4: "Launched the second, fully autonomous version of the bot and gave it a larger amount of capital",
          item5: "The bot suffered significant losses - bot shut down",
          item6: "Started another attempt at creating a semi-automated trading application",
          item7: "Another bot was created - this time written in TS and using the Bybit API",
          item8: "Bot shut down, project archived",
        },
      },
      details: {
        header: "Project details",
        whatIsTradingBot: "What is a trading bot?",
        whatIsTradingBotVal: "On an exchange, a program doesn't simply buy cryptocurrency and wait for its price to increase. It can open a so-called position - a bet on the price going up or down - and then close it when certain conditions are met. Each such operation consists of orders sent to the exchange. What I call a bot is essentially a program that runs continuously and communicates with a cryptocurrency exchange (in my case, Binance and Bybit) through an API. The program analyzes the market looking for opportunities, places orders and records the results for later analysis. Over the years, I created five versions of the bot itself and countless additional programs for analyzing the market and logs.",
        binanceIntegration: "Binance API integration",
        binanceIntegrationVal1: "The bot communicates with the exchange in several ways. The primary method is HTTP requests - they can be used, for example, to check the status of a position, retrieve historical data or place an order. Another option is WebSocket - this is how real-time data is delivered, such as every price change or order fill.",
        binanceIntegrationVal2: "For the bot to communicate with the exchange, an API key is required. Using it and the",
        binanceIntegrationVal3: "algorithm, every request contains a signature - proof that the application has access to the given resource. Not every request requires a signature - for example, access to historical price data is public and freely available. WebSockets work somewhat differently. To access sensitive data, you need a listen key, which you get by sending the appropriate request to the Binance REST API. The key is valid for a limited time, so the request has to be repeated periodically to keep it from expiring.",
        whatDoesTradingBotDo: "What does the trading bot do?",
        whatDoesTradingBotDoIntro: "I tried various methods of market analysis before eventually settling on the following algorithm:",
        whatDoesTradingBotDoList1: "If there are any open positions, the bot closes them and saves the transaction logs",
        whatDoesTradingBotDoList2: "Historical data is retrieved - typically going back a dozen to several dozen weeks",
        whatDoesTradingBotDoList3: "The data is analyzed for a buy/sell signal",
        whatDoesTradingBotDoList4: "If such a signal is found, the position parameters are calculated to control risk",
        whatDoesTradingBotDoList5: "The bot sends an order to the exchange",
        whatDoesTradingBotDoVal1: "The above sequence was executed every day at midnight UTC. This approach made it much easier to analyze the results and create simulations for testing strategies against historical data.",
        whatDoesTradingBotDoVal2: "This was not the only algorithm I tried. I also tested other approaches - more frequent market analysis and trailing stop-loss orders. A stop-loss order is used to limit losses - if the price of an asset moves against the position, such an order is triggered, closing the position with an acceptable loss. With this strategy, the bot analyzed the market for opportunities every few minutes and, after opening a position, tracked the asset's price in real time and adjusted the stop-loss order.",
        trailingStopLossVideoCaption: "Bot actively managing a short position",
        semiAutomatic: "Semi-automatic variant",
        semiAutomaticVal: "The bot had its own HTTP API, allowing it to be controlled from a web browser. The user (that is, me) adjusted the position parameters and sent the appropriate request to the bot. The bot opened and tracked the position and also recorded logs, but the decision of whether and when to enter the market remained mine.",
        interfaceImg1: "One of the first versions of the web interface I created",
        interfaceImg2: "A newer interface for controlling the bot, with most position parameters calculated automatically",
      },
      tools: {
        header: "Additional tools",
        dataAnalysis: "Data analysis",
        dataAnalysisVal1: "I wanted to create an autonomous trader. Very quickly, it became clear that writing a program that communicates with an exchange was a relatively simple part of the problem. Finding a strategy that actually worked turned out to be much more difficult. The next few years were a series of experiments aimed at answering one question: how can I determine whether a given strategy makes any sense at all?",
        dataAnalysisVal2: "Trading on an exchange without an appropriate strategy is a recipe for losing money, so I created many tools that used historical data to determine position parameters. The collected data was used to simulate the bot's operation, allowing me to see what had a chance of working and what didn't. In addition, the bot generated large amounts of logs, primarily containing information about open and closed positions. I needed a tool that could collect and combine this data.",
        strategySearch: "In search of the best strategy",
        strategySearchVal: "I used Python scripts to search for strategies, which allowed me to quickly create new ways of looking for market patterns. The software also made it possible to run simple simulations using historical data.",
        heatmapImg: "Analysis of strategy results for different parameters and time intervals",
        marketSimulation: "Market simulation",
        marketSimulationVal: "To determine whether a given strategy worked, I had to perform so-called backtests - simulations using historical data. I wrote the program for running these tests in JavaScript, the same language used for the bot's main code. Thanks to the modular structure of the bot's code, it was possible to replace a single file so that instead of connecting to a real exchange, it would \"trade\" using historical data.",
      },
      summary: {
        header: "Summary",
        result: "Result",
        resultVal: "Did I achieve my intended goal? Definitely not. The bot suffered a total loss equivalent to around $60.",
        retrospective: "The trading bot in retrospect",
        retrospectiveVal: "Going back to this project certainly wasn't easy, because despite putting in a huge amount of effort, I didn't manage to achieve the planned result. On the other hand, looking at the code I created over the years, I can see that it became progressively better and cleaner. I'm glad that towards the end of the project I warmed up to TypeScript. I didn't manage to create a program that would make money. I did, however, manage to create a program that could lose it in a surprisingly large number of ways.",
      },
    },
    starling: {
      stack: {
        electronics: "circuit design",
        mechanics: "mechanics design",
        print: "3D printing",
      },
      introduction: {
        project: "project",
        desc: "description",
        descValue: "A self-built astrophotography equipment",
        time: "time",
        status: "status",
        statusValue: "in progress",
        techStack: "tech stack",
      },
      intro: {
        header: "Intro",
        inShort: "In short",
        inShortVal: "Starling is a series of self-designed and self-built astrophotography trackers. They have allowed me to capture incredible images of the night sky using nothing more than a regular camera. By far the most complex and important project I have worked on so far, it brings together a wide range of disciplines, from mechanics and electronics to software development.",
        inShortImg: "A photo of the Andromeda Galaxy (M31) - the culmination of three years of work on the project",
        inShortImgAlt: "A photo of the Andromeda Galaxy (M31) - the culmination of three years of work on the project",
        bg: "Background",
        bgVal: "Astronomy has fascinated me since I was a child, and I have been interested in photography ever since I got my first camera many years ago. Combining the two was a natural step. It all started with a gear train made from Lego bricks, screwed to a piece of plywood and controlled by a tangle of wires on a breadboard. As my skills developed, so did Starling - each iteration introduced new improvements and refinements.",
        bgImg: "Starling 5 during a field session",
        bgImgAlt: "Starling 5 during a field session",
        timeline: {
          header: "timeline",
          item1: "Project started",
          item2: "Starling 1 completed",
          item3: "Starling 3 completed",
          item4: "Bought a 3D printer and started working on a completely new version of the project",
          item5: "Starling 5 completed - the first working version with 3D-printed parts",
          item6: "Starling 6 completed with a GoTo system",
          item7: "Starling 7 completed",
        },
        astrophotography: "A few words about astrophotography - what problem does a star tracker solve?",
        astrophotographyVal1: "Photos of celestial objects are actually the result of a process called stacking - combining multiple images into one. This improves the signal-to-noise ratio and overall image quality. Capturing a full series of images can take an entire night. When shooting from a regular tripod, the object being photographed would quickly drift out of the frame. This happens because the stars appear to continuously move across the sky around the celestial pole. The job of a star tracker is to keep the object in the frame for many hours. To achieve this, the camera must continuously - albeit very slowly - change its position relative to the Earth.",
        astrophotographyVal2: "A star tracker is a motorized equatorial mount. To do its job properly, it must be positioned in a very specific way relative to the Earth. The axis around which the mount rotates, known as the right ascension (RA) axis, must be parallel to the Earth's axis - pointing north (or south, depending on the hemisphere) and tilted at an angle equal to the observer's latitude. If the tracker is not aligned correctly, the resulting images will appear blurred, and the object being photographed will eventually drift out of the field of view.",
        astrophotographyVal3: "All of the night-sky images presented here are my own work, captured with a Panasonic Lumix GX800.",
        astrophotographyImg: "A photo taken with a tripod - just 60 seconds of exposure reveals the apparent motion of the stars",
        astrophotographyImgAlt: "A photo taken with a tripod - just 60 seconds of exposure reveals the apparent motion of the stars",
      },
      beginnings: {
        header: "The Beginnings",
        firstGeneration: "The first generation of Starling",
        firstGenerationVal1: "Starling was one of my first \"physical\" projects - something that exists as a real, tangible object rather than being entirely made of code. When I started, I had no experience building things at all. My main materials were Lego bricks and pieces of wood held together with screws.",
        firstGenerationVal2: "The first version - back then, I had no idea there would be more - was built mostly from Lego bricks. The construction was connected to a 28BYJ-48 stepper motor controlled by a Raspberry Pi Pico mounted on a breadboard. There was no user interface; control was handled from a laptop, which was used to upload the appropriate code to the controller.",
        firstGenerationVal3: "The finished device had many limitations. One of them was the maximum tracking time. Since the rotating platform holding the camera had a range of motion of only a few degrees, tracking could last no more than several minutes. Another limitation was the battery life of my aging laptop, which was required to control the device.",
        firstGenerationVal4: "Despite these limitations, the quality of individual images was surprisingly good, which encouraged me to keep developing the project.",
        firstGenerationImg: "The first version of the project during a field session",
        firstGenerationImgAlt: "The first version of the project during a field session",
        secondGeneration: "Starling 2 and experiments with a DC motor",
        secondGenerationVal1: "The next version of the project was intended to be completely different. The plan was to address the shortcomings of the first generation while also adding several new features.",
        secondGenerationVal2: "The biggest change was replacing the stepper motor with a DC motor equipped with an encoder - I reused an entire module salvaged from a printer. Although its rotational speed could be controlled precisely, in practice the motor introduced a lot of vibration, making this version unsuitable for astrophotography. The whole setup also became much larger, heavier, and more power-hungry.",
        secondGenerationVal3: "Starling 2 was not without its advantages, though. The main improvements over the first version were:",
        secondGenerationList1: "A larger range of motion for the camera platform, directly increasing the maximum possible session length",
        secondGenerationList2: "The addition of a Raspberry Pi Zero W, enabling control of the mount over WiFi - the laptop was no longer required",
        secondGenerationList3: "Easier polar alignment thanks to an accelerometer and GPS taken from an old phone",
        secondGenerationVal4: "After replacing the DC motor with a stepper motor, Starling 2 became quite usable.",
        secondGenerationImg: "Starling 2 with the DC motor",
        secondGenerationImgAlt: "Starling 2 with the DC motor",
        thirdGeneration: "The third version - a new approach to electronics design",
        thirdGenerationVal: "The next iteration of Starling was functionally similar to the previous one. The main difference was the quality of construction. The mount was starting to look less like a prototype and more like a finished product. This was particularly apparent in the electronics - I got rid of the breadboard and loose wires, replacing them with a perfboard and solder traces. This approach made the electronics more durable and reliable while also making them smaller and more aesthetically pleasing.",
        thirdGenerationImg1: "The Starling 3 controller board in the form of a HAT for the Raspberry Pi Zero W",
        thirdGenerationImg1Alt: "The Starling 3 controller board in the form of a HAT for the Raspberry Pi Zero W",
        thirdGenerationImg2: "The third version of the project was less than half the size of the second",
        thirdGenerationImg2Alt: "The third version of the project was less than half the size of the second",
      },
      threeD: {
        header: "The 3D Printing Era",
        secondStarling3: "A real breakthrough and a numbering problem - the second Starling 3",
        secondStarling3Val1: "Although I was initially skeptical, in October 2024 I bought my first 3D printer, a Bambu Lab P1P. It opened up a huge range of possibilities - I could quickly create custom-made parts tailored precisely to my current needs.",
        secondStarling3Val2: "I immediately started designing a new star tracker. It was meant to be an evolution of the third version, so it did not receive a new number. Over time, however, it turned out to have very little in common with the original Starling 3 - but the name stuck.",
        secondStarling3Val3: "The project was highly ambitious. The new mount was not only supposed to track celestial objects, but also feature a GoTo system - automatic pointing at objects in the sky. Ultimately, I was unable to finish the project. The solutions I used turned out to be unnecessarily complicated, introducing additional friction and play into the mechanics - both highly undesirable in such a precision device. Despite having access to a 3D printer, the gears and shafts were still made from Lego parts. I completed one of the modules, responsible for moving the camera along the declination (DEC) axis, perpendicular to the RA axis. The main RA bearing was also completed, as was part of the drive module for that axis. Below are several photos from different stages of the project.",
        secondStarling3Img1: "Inside the first module (DEC axis) - motor, gearbox, controller, and position sensors",
        secondStarling3Img1Alt: "Inside the first module (DEC axis) - motor, gearbox, controller, and position sensors",
        secondStarling3Img2: "The gearbox connecting the two RA-axis motors - one responsible for tracking and the other for the GoTo system",
        secondStarling3Img2Alt: "The gearbox connecting the two RA-axis motors - one responsible for tracking and the other for the GoTo system",
        fourthGeneration: "The missing Starling - what happened to the fourth iteration",
        fourthGenerationVal: "Starling 4 was never completed. Shortly after starting work on it, I decided to build another version using parts from the previous iteration.",
        fourthGenerationImg: "Bearing clamp - the only part designed specifically for Starling 4",
        fourthGenerationImgAlt: "Bearing clamp - the only part designed specifically for Starling 4",
        fifthGeneration: "Starling 5 - a completely new approach",
        fifthGenerationVal1: "After the failed attempt to build a mount with a GoTo system, I decided that I should first master the basic functionality - tracking - and only then add more advanced features. This idea gave rise to the fifth version of the project, which itself went through several revisions. For the time being, I decided to abandon the GoTo system and completely redesign the drive system. These changes also required new control electronics - I needed an entirely new board.",
        fifthGenerationVal2: "This time I chose a completely different type of gearbox - I replaced the worm gear with a planetary gearbox. I also changed the motor, replacing the small 28BYJ-48 with a larger NEMA 17 motor.",
        fifthGenerationVal3: "I was not happy with the final result - the gearbox introduced a lot of friction and play, making the output motion uneven. On top of that, the motor shaft was round rather than D-shaped, so the gears would sometimes slip on the shaft. I decided to change my approach.",
        fifthGenerationImg: "A three-stage planetary gearbox during the early stages of Starling 5 development",
        fifthGenerationImgAlt: "A three-stage planetary gearbox during the early stages of Starling 5 development",
        success: "Finally, success",
        successVal1: "I built a working version around the RA-axis bearing clamp from one of the previous versions. I decided to keep what worked well and change what needed improvement. My goal was to simplify both the drive system and the control electronics as much as possible.",
        successVal2: "I abandoned the planetary gearbox and used an extremely simplified worm drive instead, reducing play and friction to a minimum. The controller board contains only the essentials required to drive the motor. The user operates the device with a single button to switch between operating modes, while an RGB LED on the controller indicates the current mode. The whole system is small and lightweight and compatible with both telescope tripods and regular camera tripods. It is also energy-efficient and powered via USB-C, so it can be run from either a power bank or a 12V battery with a converter. Tracking with this iteration produced satisfactory, although still not perfect, results.",
        successImg1: "An almost finished star tracker with its simple control electronics",
        successImg1Alt: "An almost finished star tracker with its simple control electronics",
        successImg2: "Part of the Cygnus constellation, photographed with my camera mounted on Starling 5",
        successImg2Alt: "Part of the Cygnus constellation, photographed with my camera mounted on Starling 5",
        sixthGeneration: "Starling 6 - a second attempt at a GoTo system",
        sixthGenerationVal: "The previous version, although it worked reasonably well, had one major drawback - aiming at an object in the sky was extremely difficult. All previous iterations used an Ulanzi ball head to mount the camera. It worked great at shorter focal lengths, but as the magnification increased, aiming became increasingly difficult - a single wrong movement was enough to completely lose the object from the frame. The solution was supposed to be a GoTo system, allowing me to frame an object without touching the mount itself. Everything was controlled through a browser-based smartphone app.",
        sixthGenerationImg: "Starling 6 under construction",
        sixthGenerationImgAlt: "Starling 6 under construction",
        mechanics: "Mechanics",
        mechanicsVal: "Starling was built around two large ball bearings to minimize play as much as possible. Like the older versions, the RA-axis motor used a simple worm drive. The DEC-axis motor had a more demanding job, as it had to make precise movements while carrying a heavy camera. After several attempts and some trial and error, I also used a worm drive here, this time with an additional reduction stage to increase the motor's torque. With the exception of the worm gears themselves, I designed and 3D-printed all mechanical components, then assembled them using M3 screws. The whole setup became large and heavy, requiring an additional counterweight.",
        mechanicsImg: "A motor mount designed to be 3D-printable without supports",
        mechanicsImgAlt: "A motor mount designed to be 3D-printable without supports",
        electronics: "Electronics",
        electronicsVal: "The main board did not just have to control the motors - most importantly, it had to know where they were. To make this possible, each axis had its own position sensor: the RA axis used a slotted optocoupler, while the DEC axis used a limit switch. Before operation, the star tracker performed a homing sequence to establish its zero position.",
        electronicsImg1: "A 3D-printed main board with copper tape traces",
        electronicsImg1Alt: "A 3D-printed main board with copper tape traces",
        electronicsImg2: "The final - fourth - version of the Starling 6 main board",
        electronicsImg2Alt: "The final - fourth - version of the Starling 6 main board",
        software: "Software",
        softwareVal: "The brain of the system was a Raspberry Pi Pico 2W. This time I used C++ to program it because I had stability issues with the Access Point when using Python. Later, it turned out that the problem also occurred with C++ - perhaps I got a faulty unit, or perhaps I did something wrong; I still do not know. I used both cores of the microcontroller: one handled the HTTP server, including SSE, as well as the GPS module, while the other was dedicated entirely to controlling the stepper motors. The interface displayed the current status, allowed the user to select a target from a list of objects, and provided manual motor control.",
        softwareImg: "Starling 6 web interface",
        softwareImgAlt: "Starling 6 web interface",
        sixthResults: "Starling 6 - results",
        sixthResultsVal: "Controlling the mount with a smartphone turned out to be incredibly convenient - I could frame virtually any object in the sky with a level of precision that had previously been impossible. Unfortunately, probably due to the weight of the entire device, tracking was not accurate enough, and many photos came out with noticeable motion blur.",
        sixthResultsImg: "The completed sixth iteration",
        sixthResultsImgAlt: "The completed sixth iteration",
        seventhGeneration: "Starling 7 - a return to simplicity",
        seventhGenerationVal1: "The inaccurate tracking of the previous versions kept bothering me and motivated me to search for and test new solutions. For now, I decided to abandon GoTo and focus on what matters most - tracking - and only move forward once I had mastered that aspect.",
        seventhGenerationVal2: "This time I opted for a pair of large tapered roller bearings. The goal was to minimize play and friction regardless of the angle at which the tracker was tilted. The control electronics were almost identical to those used in Starling 5 - a microcontroller, a stepper motor driver, and a single button.",
        seventhGenerationVal3: "To somewhat make up for the lack of a GoTo system, I bought a different camera head - the Ulanzi U190. Although it is not as convenient as automatic pointing, it allows me to frame the desired object relatively comfortably.",
        seventhGenerationImg: "Starling 7 during testing",
        seventhGenerationImgAlt: "Starling 7 during testing",
      },
      accessories: {
        header: "Accessories",
        calibrationFrames: "Calibration frames",
        calibrationFramesVal1: "Astrophotography involves capturing not only images of the object itself (light frames), but also calibration frames (darks, biases, and flats). Flats are images of an evenly illuminated frame, used to remove vignetting and dust from the lens. They require a so-called flat-field panel - a device that provides an even light source. Of course, it can be built yourself.",
        calibrationFramesVal2: "In my case, the light source is an old tablet displaying a white screen. The light is further diffused using a sheet of diffuser material salvaged from a broken TV. The whole thing is held in place by a 3D-printed mount.",
        calibrationFramesImg: "DIY flat-field panel",
        calibrationFramesImgAlt: "DIY flat-field panel",
        dew: "Fighting dew",
        dewVal1: "Night-time conditions are ideal for moisture to form and settle on equipment. One way to combat this is to use a dew shield.",
        dewVal2: "The shield I designed serves three purposes - it protects the lens from dew, while also acting as an adapter for mounting the flat-field panel or a 58 mm photographic filter.",
        dewImg: "An adapter screwed into the 37 mm filter thread",
        dewImgAlt: "An adapter screwed into the 37 mm filter thread",
        power: "Power",
        powerVal: "There is rarely a power outlet available out in the field. To power Starling, the camera, and its accessories, I use a car battery and a simple converter board. The battery provides enough energy for an entire night of operation, while the converter board offers four USB ports for powering various 5V devices. The controller monitors the input voltage and uses its built-in RGB LED to indicate the battery's charge level.",
        powerImg: "A 12V-to-5V converter with USB outputs",
        powerImgAlt: "A 12V-to-5V converter with USB outputs",
        starlingPolar: "Starling Polar",
        starlingPolarVal: "Another task worth automating is polar alignment. At the moment, I do it manually, which is time-consuming and prone to error. The Starling Polar project is currently in development - its purpose is to automatically align the RA axis parallel to the Earth's axis.",
        starlingPolarImg: "The Starling Polar module under construction",
        starlingPolarImgAlt: "The Starling Polar module under construction",
      },
      summary: {
        header: "Summary",
        statistics: "Statistics",
        statisticsVal1: "Around 600 3D-printable part designs have been created for Starling. I have no idea how many kilograms of filament I have used. As for the total cost, it would most likely have been cheaper to buy a ready-made mount - but then there would have been no fun in it.",
        statisticsVal2: "Recently, I started tracking the success rate of my photos - what percentage of the images turn out well and what percentage are unusable. The statistics below cover photos taken at a 150 mm focal length (300 mm full-frame equivalent) with an exposure time of 30 seconds.",
        statisticsList1: "Starling 5 - approximately 49.7% usable frames",
        statisticsList2: "Starling 6 - approximately 27.6% usable frames",
        statisticsList3: "Starling 7 - approximately 38.0% usable frames",
        trialAndError: "Trial and error",
        trialAndErrorVal: "Starling is a story full of successes and failures.",
        trialAndErrorImg1: "Things do not always work on the first try",
        trialAndErrorImg1Alt: "Things do not always work on the first try",
        trialAndErrorImg2: "A box full of failed prints and prototypes",
        trialAndErrorImg2Alt: "A box full of failed prints and prototypes",
      },
      future: {
        header: "The Future of the Project",
        notTheEnd: "This is not the end",
        notTheEndVal: "Starling already allows me to take photos that would be impossible to capture with a regular tripod. The project is still evolving, though - the next goals are improving tracking accuracy, getting the GoTo system working, and automating polar alignment. I am sure the project will go through more iterations in the future.",
        notTheEndImg: 'The Pleiades star cluster',
        notTheEndImgAlt: 'The Pleiades star cluster',
      },
    },
    homelab: {
      introduction: {
        project: "project",
        desc: "description",
        descValue: "Home network and server infrastructure",
        time: "time",
        timeValue: "since 2020",
        status: "status",
        statusValue: "online",
        techStack: "tech stack",
      },
      intro: {
        header: "Intro",
        inShort: "In short",
        inShortVal: "My personal homelab, which has evolved over the years from a Raspberry Pi into a full-fledged server rack. It hosts projects, services, and infrastructure that I use on a daily basis.",
        inShortImg: "The rack as of October 2026",
        bg: "Background",
        bgVal1: "The homelab was never a goal in itself. It started with Minecraft servers and hosting a website for the JourneyCraft project. Over time, the infrastructure grew along with my needs - the network evolved, more servers were added, and a small computer eventually gave way to a full-sized rack.",
        bgVal2: "The server room has been in the same room where I sleep from the start, which was an important factor when choosing the hardware. Some of the machines also run 24/7, so power consumption is something I have to keep in mind.",
        timeline: {
          header: "timeline",
          item1Date: "January 2020",
          item1: "First attempts at hosting a website on my own hardware",
          item2Date: "March 2021",
          item2: "Registered my first domain",
          item3Date: "June 2021",
          item3: "Bought a MikroTik router, my first experience with this kind of hardware",
          item4Date: "October 2022",
          item4: "Moved to a new place and built a network in a rack cabinet",
          item5Date: "April 2026",
          item5: "Moved again and built a network in my new apartment",
        },
      },
      beginning: {
        header: "The beginning",
        why: {
          header: "Where did the idea for a home server room come from?",
          value: "At the time, I was playing Minecraft with my friends. We used a paid hosting service (Craftserve), which I managed. I needed a simple dashboard - something like a bulletin board where I could post information such as an upcoming server payment. Craftserve also provided an interactive map of the game world that could be embedded on a website, so I decided to use it.",
          img: 'My first self-hosted website - a "dashboard" for a Minecraft server',
        },
        start: {
          header: "What did I start with?",
          value1: "When I published the dashboard, I knew very little about creating or hosting websites. I asked my dad to configure DMZ on our home router, installed Raspbian on my RPI, installed Apache2, and carelessly exposed the Raspberry Pi to the public internet.",
          value2: "No firewall. No monitoring. No domain. No supporting infrastructure - just a Raspberry Pi connected to a regular home router.",
          img: "Raspberry Pi 1B hanging from cables - my first server",
        },
        network: {
          header: "Expanding the network and adding another server",
          value1: "Paid hosting has its advantages, but it also has a few drawbacks - most notably, limited flexibility when it comes to installing mods. So I decided to use an old computer as a Minecraft server. I also bought a second-hand home router to expand my network. I learned a bit about how port forwarding worked, and I could now expose only the ports I actually needed.",
          value2: "I still knew relatively little about networking...",
          img: 'A creative "Wake-on-LAN" setup - Raspberry Pi connected to a relay',
        },
        mikrotik: {
          header: "The beginning of my MikroTik journey",
          value: "Buying that router turned out to be a great investment in my knowledge. The sheer number of MikroTik features was overwhelming at first, but it forced me to learn a lot about computer networking. By then, my equipment was well configured. It was the first, but not the last MikroTik I bought - I really liked that there is no configuration it can't handle, as I would find out later.",
          img: "My first MikroTik router - an RB2011 series model",
        },
        infrastructure: {
          header: "Expanding the server infrastructure, getting a UPS, and setting up my own VPN",
          value1: "Although I initially only hosted things occasionally, over time at least one server ended up running 24/7. One of the services that ran continuously was an OpenVPN server, which allowed me to connect to my home network from anywhere in the world. It also became a security measure - I used to expose SSH directly to the internet (needless to say, that's a bad idea), but with a VPN I could make sure that the configuration interface was accessible only from the local network.",
          value2: "To keep the network running during power outages, I bought a UPS. It correctly handled prolonged outages by notifying the server that it needed to shut down safely. The problem came later: since the UPS continued powering the server, the computer remained switched off after power was restored and had no signal that could turn it back on. I solved the problem with a small custom circuit. A microcontroller was connected to a regular wall outlet independent of the UPS and controlled a relay connected to the server's power button. When power returned, the microcontroller started up, checked the server's state, and if it was powered off, simulated a short press of the power button. The first version was built on a breadboard in 2022. Over time, I replaced it with a much more robust version soldered onto a perfboard. This simple but effective solution is still in use today.",
          img: "Prototype of a circuit that powers the server back on after an outage, later replaced with a sturdier version",
        },
      },
      rack: {
        header: "The real breakthrough - a rack cabinet",
        dream: {
          header: "A dream come true",
          value: "After moving out of my family home, I was able to dedicate an entire room to my server setup. A large rack cabinet became its centerpiece. It housed three servers, a router, and a switch. The network equipment served not only the servers but also the rest of the home infrastructure - wall ports and access points.",
          img: "Installing hardware in the rack cabinet",
        },
        subnets: {
          header: "Subnets",
          value: "The home network included several computers, printers, and access points. I created several VLANs on the MikroTik - separate networks for servers, home devices, and guests - so that the failure or compromise of one device would not automatically expose the rest of the network. This required configuring the Cisco switch accordingly and creating firewall rules to restrict access between the networks.",
        },
        backupIsp: {
          header: "Setting up a backup internet connection",
          value1: "My experience in the previous apartment made me want to have a backup ISP in addition to a UPS. Moreover, I wanted it to be independent of the building's power grid, so that I could still access the internet during a power outage. I opted for a mobile internet connection - bought a USB modem and connected it to the router.",
          value2: "The real challenge turned out to be the configuration - I had two ISPs, meaning two different (and dynamic) IP addresses. On top of that, the mobile connection gave me no way to configure things like port forwarding. To solve this problem, I rented a VPS, set up a WireGuard VPN server on it, and established a connection to my server room. I pointed my domains to the VPS's public IP address and configured it to forward all incoming traffic through the tunnel. I also had to make several changes to my router's configuration - all traffic coming from the tunnel had to be properly marked so that the response packets would also be routed back through the tunnel. I additionally wrote a script that pinged the VPS through the primary ISP interface - if the ping failed, it changed the default route to use the mobile connection instead.",
        },
      },
      current: {
        header: "The current state of the server room",
        simplification: {
          header: "Simplifying the network configuration",
          value: "After several years of experience, I deliberately simplified the infrastructure because some of its components were no longer necessary. The dual-ISP setup worked well, but it was relatively expensive to maintain. What's more, it had come in handy only once over the course of several years. I also often found myself adding firewall rules to allow communication between subnets, which undermined the whole point of maintaining such a setup. These factors led me to simplify the network after moving. I gave up the VPS, the secondary ISP, and the managed switch, replacing the latter with a small, energy-efficient TP-Link switch mounted in the rack in a 3D-printed bracket.",
          img: "Simplified network - I removed the Cisco switch, and the patch panel is no longer in use",
        },
        services: {
          header: "Currently hosted services",
          value: "I currently have three servers, each with different specifications and a different purpose. The main server (srv1) runs continuously and hosts services I use every day - Apache2, Samba, and OpenVPN. The second machine (srv2) is significantly more powerful, but also consumes more power, so I only turn it on when needed. Its main purpose is hosting demanding Minecraft servers. The last server (srv3) is dedicated to backups, with two drives configured as a RAID 1 array.",
          img: "Netcat is listening on port 80",
        },
      },
    },
  },
};